import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

shell = "nu"

[window]
#opacity = 0.1

[env]
TERM = "xterm-256color"


[font]
normal      = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold        = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic      = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }
size = 15.0
